### ISSUE TITLE
flutter app not running

### ISSUE THREAD

**Issue by ammarbhatkar** [derTuca/flutter_sim_country_code#20]
since i upgraded my flutter to 3.27.1 my appk is not running and give compilation error :

C:\Userspub.dev\flutter_sim_country_code-0.1.2\android\src\main\java\com\example\flutter_sim_country_code\FlutterSimCountryCodePlugin.java:14: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
C:\Usersub.dev\flutter_sim_country_code-0.1.2\android\src\main\java\com\example\flutter_sim_country_code\FlutterSimCountryCodePlugin.java:25: error: cannot find symbol
  public static void registerWith(Registrar registrar) {
                                  ^
  symbol:   class Registrar
  location: class FlutterSimCountryCodePlugin
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_sim_country_code:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
